ALTER TABLE [Category] ADD [Version] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [Product] ADD [Version] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [SpringProduct] ADD [Version] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [UnitOfPrice] ADD [Version] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [ProductPrice] ADD [Version] INT NOT NULL DEFAULT 0
GO