CREATE TABLE [Category]
(
	[Id] INT IDENTITY NOT NULL,
	[Name] NVARCHAR(128) NOT NULL,
	[Description] NVARCHAR(512) NULL,
	[Image] NVARCHAR(64) NULL,

    PRIMARY KEY (Id)
);
GO;

CREATE TABLE [Product]
(
	[Id] INT IDENTITY NOT NULL,
	[CategoryId] INT NOT NULL,
	[Name] NVARCHAR(128) NOT NULL,
	[Description] NVARCHAR(512) NULL,
	[Image] NVARCHAR(64) NULL,

    PRIMARY KEY (Id),
	FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);
GO;

CREATE TABLE [SpringProduct]
(
	[Id] INT NOT NULL,
	[Diametr] DECIMAL NULL,
	[Weight] DECIMAL NULL,

    PRIMARY KEY (Id),
	FOREIGN KEY (Id) REFERENCES Product(Id)
);
GO;

CREATE TABLE [UnitOfPrice]
(
	[Id] INT IDENTITY NOT NULL,
	[Name] NVARCHAR(64) NOT NULL,
	[Description] NVARCHAR(128) NULL,

    PRIMARY KEY (Id)
);
GO;

CREATE TABLE [ProductPrice]
(
	[Id] INT IDENTITY NOT NULL,
	[ProductId] INT NOT NULL,
	[UnitOfPriceId] INT NOT NULL,

    PRIMARY KEY (Id),
	FOREIGN KEY (ProductId) REFERENCES Product(Id),
	FOREIGN KEY (UnitOfPriceId) REFERENCES UnitOfPrice(Id)
);
GO;