language: csharp
solution: ./Sources/Vilandagro.sln
install:
  - nuget restore ./Sources/Vilandagro.sln
  - nuget install nUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
 - xbuild /p:Configuration=Release ./Sources/Vilandagro.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Sources/Vilandagro.Core.Tests/bin/Release/Vilandagro.Core.Tests.dll ./Sources/Vilandagro.Infrastructure.Tests/bin/Release/Vilandagro.Infrastructure.Tests.dll