language: csharp
solution: ./Sources/Vilandagro.sln
install:
  - nuget restore ./Sources/Vilandagro.sln
  - nuget install nUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
before_script:
  - mysql -e "drop database IF EXISTS test;"
  - mysql -e "create database test;"
script:
 - xbuild /p:Configuration=Release ./Sources/Vilandagro.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe -exclude:ExcludeFromCI ./Sources/Vilandagro.Core.Tests/bin/Release/Vilandagro.Core.Tests.dll ./Sources/Vilandagro.Infrastructure.Tests/bin/Release/Vilandagro.Infrastructure.Tests.dll ./Sources/Vilandagro.Database.MySql.Tests/bin/Release/Vilandagro.Database.MySql.Tests.dll ./Sources/Vilandagro.Infrastructure.EF.Tests/bin/Release/Vilandagro.Infrastructure.EF.Tests.dll ./Sources/Vilandagro.WebApi.Tests/bin/Release/Vilandagro.WebApi.Tests.dll ./Sources/Vilandagro.Trainings.Tests/bin/Release/Vilandagro.Trainings.Tests.dll